### ISSUE TITLE
Add THz: Swamp Audio

### ISSUE THREAD

**Issue by esot321c** [ergolabs/default-token-list#1]
- [x] I understand that token listing is not required to use the ErgoDEX Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the ErgoDEX default token list.
- [x] I will not ping the ErgoDEX team about this listing request.

**Please provide the following information for your token.**

Network: Ergo
Project Name: Swamp Audio  
Link to explorer: https://explorer.ergoplatform.com/en/token/02f31739e2e4937bb9afb552943753d1e3e9cdd1a5e5661949cb0cef93f907ea
URI to token's logo:  https://raw.githubusercontent.com/ergolabs/ergo-dex-asset-icons/master/light/02f31739e2e4937bb9afb552943753d1e3e9cdd1a5e5661949cb0cef93f907ea.svg
Token Name:  Terahertz
Token Decimals:  4

Link to the official homepage of project/token:  https://swamp.audio
Links to the official socials of project/token:  [Twitter](https://twitter.com/swampoflife), [Instagram](https://instagram.com/swamp.of.life), [Soundcloud](https://soundcloud.com/swamp-music-1), [Spotify](https://open.spotify.com/show/0m6cWf576CR45bALfVOIfv)
Link to CoinMarketCap or CoinGecko page of project/token (if exists):

**Comment by yasha-black** [comment]
@esot321c Token Name defers from what I see in [the explorer](https://explorer.ergoplatform.com/en/token/02f31739e2e4937bb9afb552943753d1e3e9cdd1a5e5661949cb0cef93f907ea). Make sure that you've provided the right Token Name.

**Comment by esot321c** [comment]
Updated

**Comment by yasha-black** [comment]
Added
