### ISSUE TITLE
Add {EPOS}: {ERGOPOS}

### ISSUE THREAD

**Issue by LEEKOHCHING** [ergolabs/default-token-list#10]
- [x] I understand that token listing is not required to use the ErgoDEX Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the ErgoDEX default token list.
- [x] I will not ping the ErgoDEX team about this listing request.

**Please provide the following information for your token.**

Network:  ERGO
Project Name:  ErgoPOS
Link to explorer:  https://explorer.ergoplatform.com/en/token/00bd762484086cf560d3127eb53f0769d76244d9737636b2699d55c56cd470bf
URI to token's logo:  https://ergopos.io/upload/ergoposlogo.png
Token Name:  EPOS
Token Decimals:  4

Link to the official homepage of project/token:  https://www.ergopos.io/
Links to the official socials of project/token:  https://t.me/ergopos
Link to CoinMarketCap or CoinGecko page of project/token (if exists):

**Comment by yasha-black** [comment]
Added #11
