### ISSUE TITLE
Add Ogre: Ogre

### ISSUE THREAD

**Issue by ErgoWhale** [ergolabs/default-token-list#13]
- [x] I understand that token listing is not required to use the ErgoDEX Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the ErgoDEX default token list.
- [x] I will not ping the ErgoDEX team about this listing request.

**Please provide the following information for your token.**

Network:  Ergo
Project Name:  Ogre
Link to explorer:  https://explorer.ergoplatform.com/en/token/6de6f46e5c3eca524d938d822e444b924dbffbe02e5d34bd9dcd4bbfe9e85940
URI to token's logo:  https://ogre-token.web.app/assets/ogre.png
Token Name:  Ogre
Token Decimals:  0

Link to the official homepage of project/token:  https://ogre-token.web.app/
Links to the official socials of project/token:  https://twitter.com/Ogre_Token (11k followers and growing rapidly)
Link to CoinMarketCap or CoinGecko page of project/token (if exists): does not exist

Note:
Ogre token is bringing a large number of new users to Ergo through a social media campaign (10,000+ followers and growing). We are trying to teach users how to use the DEX, but they are getting confused because they can't find the Ogre token in the default list, and they're getting frustrated. These are new users to Spectrum, so they need an easy onboarding experience, and this will help them tremendously.

**Comment by Remmy4L** [comment]
Add Ogre token

**Comment by Jerryyhhh** [comment]
100 trillion Ogre is worth a companion😇

**Comment by Jerryyhhh** [comment]
I'm starving Ogre token, please don't let me die 😅😅 ..... Here's my Ergo address, thank you.💎

9fKwqtNyuDrVez1UWSnZu7nr6Qqtngj39dpG43LGNzGRR9k4xND

**Comment by ekeh435** [comment]
Glad to be part of this growing project that has great potentials.

**Comment by Kaystar001** [comment]
Add Ogre 🚀🚀🚀

**Comment by bnc666** [comment]
🚀🚀🚀

**Comment by vvisenu** [comment]
I'm providing liquidity, not much,, but this is just the beginning

**Comment by yasha-black** [comment]
ogre token was added
