### ISSUE TITLE
Add FLUX: Flux

### ISSUE THREAD

**Issue by Kyuubi2709** [ergolabs/default-token-list#15]
- [X] I understand that token listing is not required to use the ErgoDEX Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the ErgoDEX default token list.
- [X] I will not ping the ErgoDEX team about this listing request.

**Please provide the following information for your token.**

Network:  ERGO
Project Name:  Flux
Link to explorer: https://explorer.ergoplatform.com/en/token/e8b20745ee9d18817305f32eb21015831a48f02d40980de6e849f886dca7f807
URI to token's logo: https://raw.githubusercontent.com/RunOnFlux/press/master/Flux_Asset_PNG/Flux%20Logo/Symbol/Round%20Symbol/PNG/Flux_symbol_blue-white.png 
https://raw.githubusercontent.com/RunOnFlux/press/master/Flux_Asset_SVG/Flux%20Logo/Symbol/Round%20Symbol/SVG/Flux_symbol_blue-white.svg
Token Name:  FLUX
Token Decimals:  8

Link to the official homepage of project/token:  https://runonflux.io/
Links to the official socials of project/token:  
https://twitter.com/RunOnFlux
https://discord.io/runonflux
https://www.facebook.com/runonflux
https://bitcointalk.org/index.php?topic=2853688.0
https://t.me/runonflux
https://www.youtube.com/channel/UCphbdfb1MXYgUPsdhQPcnGw
https://www.reddit.com/r/Flux_Official
https://www.linkedin.com/company/flux-official/mycompany/
https://www.tiktok.com/@flux_runonflux
https://www.instagram.com/runonflux_official/
Link to CoinMarketCap or CoinGecko page of project/token (if exists): 
https://www.coingecko.com/de/munze/flux-zelcash
https://coinmarketcap.com/currencies/zel/

**Comment by yasha-black** [comment]
@Kyuubi2709 the token was added #16
