### ISSUE TITLE
Add {TOKEN_TICKER}: {PROJECT_NAME}

### ISSUE THREAD

**Issue by EGIOToken** [ergolabs/default-token-list#6]
- [x] I understand that token listing is not required to use the ErgoDEX Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the ErgoDEX default token list.
- [x] I will not ping the ErgoDEX team about this listing request.

**Please provide the following information for your token.**

Network: Ergo
Project Name: ErgoGames.io
Link to explorer:  https://explorer.ergoplatform.com/en/token/00b1e236b60b95c2c6f8007a9d89bc460fc9e78f98b09faec9449007b40bccf3
URI to token's logo: https://ibb.co/y5Wp7rs 
Token Name:  $EGIO
Token Decimals: 4

Link to the official homepage of project/token:  http://ergogames.io/
Links to the official socials of project/token:  Twitter: https://twitter.com/ErgoGamesio / Discord: https://discord.gg/Sv3embeFcS / Telegram: https://t.me/ergogames_chat
Link to CoinMarketCap or CoinGecko page of project/token (if exists):

**Comment by yasha-black** [comment]
@EGIOToken the token was added
https://github.com/ergolabs/default-token-list/blob/master/src/tokens/ergo.json#L54
