### ISSUE TITLE
Add Erdoge: Erdoge

### ISSUE THREAD

**Issue by timsahabutdinov** [ergolabs/default-token-list#7]
- [ ] I understand that token listing is not required to use the ErgoDEX Interface with a token.
- [ ] I understand that filing an issue or adding liquidity does not guarantee addition to the ErgoDEX default token list.
- [ ] I will not ping the ErgoDEX team about this listing request.

**Please provide the following information for your token.**

Network:  
Project Name:  
Link to explorer:  
URI to token's logo:  
Token Name:  
Token Decimals:  

Link to the official homepage of project/token:  
Links to the official socials of project/token:  
Link to CoinMarketCap or CoinGecko page of project/token (if exists):

**Comment by yasha-black** [comment]
@timsahabutdinov your form is empty. Fill the form for consideration

**Comment by yasha-black** [comment]
Not added.
Reason: lack of information about the token.
